# Generated by Django 2.2.6 on 2019-10-23 08:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulua', models.CharField(max_length=200)),
                ('testua', models.TextField()),
                ('sortutako_data', models.DateTimeField(default=datetime.datetime(2019, 10, 23, 8, 35, 49, 947084, tzinfo=utc))),
                ('publikatutako_data', models.DateTimeField(blank=True, null=True)),
                ('publikatuta', models.BooleanField(verbose_name=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
