# Generated by Django 2.2.6 on 2019-10-24 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191024_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posta',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/logos/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='posta',
            name='sortutako_data',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 10, 44, 58, 531625, tzinfo=utc)),
        ),
    ]
