# Generated by Django 2.2.6 on 2019-11-06 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191106_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posta',
            name='sortutako_data',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 9, 58, 12, 918718, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
