# Generated by Django 2.2.6 on 2019-11-06 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20191106_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posta',
            name='sortutako_data',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 10, 35, 52, 704921, tzinfo=utc)),
        ),
    ]
